# Generated by Django 2.1.2 on 2018-11-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181126_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapregunta',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Alumno'),
        ),
    ]
