# Generated by Django 2.1.2 on 2018-11-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_respuestapregunta_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Generacion'),
        ),
    ]
