# Generated by Django 2.1.2 on 2018-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20181126_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
