# Generated by Django 2.1.2 on 2018-11-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_pregunta_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='generacion',
        ),
        migrations.RemoveField(
            model_name='generacion',
            name='anio',
        ),
        migrations.AddField(
            model_name='carrera',
            name='generacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Generacion'),
        ),
        migrations.AddField(
            model_name='generacion',
            name='generacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
