# Generated by Django 2.1.2 on 2018-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_pregunta_json_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='json_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
